services:
  fastapi:
    image: fastapi:latest
    build:
      context: .
    ports:
      - 55000:8000
  streamlit:
    image: streamlit:v1
    build:
      context: ./streamlit_app

    ports:
      - 8501:8501
    environment:
      - PRICE_PREDICTOR_API_URL=http://fastapi:8000