services:
  fastapi:
    image: isofer/fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 55000:8000
  streamlit:
    image: isofer/streamlit:latest
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      - PRICE_PREDICTOR_API_URL=http://fastapi:8000